sources:
  - name: outrun
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/68891/outrun/0.1.35
documents:
  - ./src/subgraph/stake.graphql
  - ./src/subgraph/pool.graphql
