sources:
  - name: outrun
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/68891/outrun/0.0.89
  - name: outrunStake
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/64787/outrun/v0.0.1
documents:
  - ./src/subgraph/query.graphql
